IMAGE_SIZE: [224,224,3]
BATCH_SIZE: 32
CLASSES: 20
LEARNING_RATE: 0.001
DEVICE: cuda
EPOCHS: 15
WEIGHTS: DEFAULT
EXPERIMENT_NAME: 20_food_classes
MODEL_NAME: effnetB0
SHUFFLE: True
STEP_SIZE: 6
GAMMA: 0.5
