IMAGE_SIZE: [224,224,3]
BATCH_SIZE: 64
CLASSES: 20
LEARNING_RATE: 0.001
DEVICE: cuda
EPOCHS: 15
WEIGHTS: DEFAULT
EXPERIMENT_NAME: 20_food_classes
SHUFFLE: True
STEP_SIZE: 7
GAMMA: 0.5
MODE: 'min'
FACTOR: 0.1
PATIENCE: 5
VERBOSE: True
p: 0.7