artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/17gWnStdAya6dKAIEplJvvxg-aK560lNX/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion 



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pth
  updated_base_model: artifacts/prepare_base_model/base_model_updated.pth


prepare_tensorboard:
  root_dir: artifacts/prepare_tensorboard
  tensorboard_root_log_dir: artifacts/prepare_tensorboard/tensorboard_log_dir


data_transforms:
  root_dir: artifacts/data_transforms
  transforms_pkl: artifacts/data_transforms/transforms.pkl
  

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pth